spring.application.name: meetCode
server.port: 8080
spring.security.oauth2.resourceserver.jwt.jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com
cors.allowed.origins: ${CORS_ALLOWED_ORIGINS}
admin.login.code: "${ADMIN_LOGIN_CODE}"